---
kubernetes:
  children:
    master:
      hosts:
        apk3s00:
          ansible_host: 10.50.50.30
        apk3s01:
          ansible_host: 10.50.50.31
        apk3s02:
          ansible_host: 10.50.50.32
    worker:
      hosts:
        aprp03:
          ansible_host: 10.50.50.103
        aprp04:
          ansible_host: 10.50.50.104
        aprp05:
          ansible_host: 10.50.50.105
        aprp06:
          ansible_host: 10.50.50.106
        aprp07:
          ansible_host: 10.50.50.107
        aprp08:
          ansible_host: 10.50.50.108
        aprp09:
          ansible_host: 10.50.50.109
        aprp10:
          ansible_host: 10.50.50.110
        aprp11:
          ansible_host: 10.50.50.111
        aprp12:
          ansible_host: 10.50.50.112
        # aprp13:
        #   ansible_host: 10.50.50.113
        # aprp14:
        #   ansible_host: 10.50.50.114
        # aprp15:
        #   ansible_host: 10.50.50.115
        # aprp16:
        #   ansible_host: 10.50.50.116
        # aprp17:
        #   ansible_host: 10.50.50.117
        # aprp18:
        #   ansible_host: 10.50.50.118
        # aprp19:
        #   ansible_host: 10.50.50.119
        apk3s03:
          ansible_host: 10.50.50.33
        apk3s10:
          ansible_host: 10.50.50.40
        apk3s11:
          ansible_host: 10.50.50.41
        apk3s12:
          ansible_host: 10.50.50.42
        apk3s13:
          ansible_host: 10.50.50.43
        aprp01:
          ansible_host: 10.50.50.101
        aprp02:
          ansible_host: 10.50.50.102
    # rpi3:
    #   hosts:
    #     aprp[13:19]:
