---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: rook-ceph-cluster
  namespace: rook-ceph
spec:
  interval: 15m
  chart:
    spec:
      chart: rook-ceph-cluster
      version: v1.10.7
      sourceRef:
        kind: HelmRepository
        name: rook-ceph
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    monitoring:
      enabled: true
      createPrometheusRules: true
    ingress:
      # dashboard:
      #   ingressClassName: nginx
      #   annotations:
      #     hajimari.io/appName: "Rook"
      #     hajimari.io/icon: "mdi:chess-rook"
      #   host:
      #     name: &host rook.${SECRET_DOMAIN}
      #     path: /
      #   tls:
      #     - hosts:
      #         - *host
      dashboard:
        enabled: true
        ingressClassName: "nginx"
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-production"
          external-dns.alpha.kubernetes.io/target: "ipv4.${SECRET_DOMAIN}"
          external-dns/is-public: "true"
          hajimari.io/appName: "Rook"
          hajimari.io/icon: "mdi:chess-rook"
        hosts:
          - host: &host "rook.${SECRET_DOMAIN}"
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - *host
            SecretName: "rook-dashboard-tls"
    configOverride: |
      [global]
      bdev_enable_discard = true
      bdev_async_discard = true
    cephClusterSpec:
      network:
        provider: host
      crashCollector:
        disable: false
      dashboard:
        enabled: true
        urlPrefix: /
        ssl: false
      storage:
        useAllNodes: false
        useAllDevices: false
        config:
          osdsPerDevice: "1"
        nodes:
          - name: "aprp01"
            devices:
            - name: "/dev/sda"
          - name: "aprp02"
            devices:
            - name: "/dev/sda"
          - name: "aprp03"
            devices:
            - name: "/dev/sda"
          - name: "aprp04"
            devices:
            - name: "/dev/sda"
          - name: "aprp05"
            devices:
            - name: "/dev/sda"
          - name: "aprp06"
            devices:
            - name: "/dev/sda"
          - name: "aprp07"
            devices:
            - name: "/dev/sda"
          - name: "aprp08"
            devices:
            - name: "/dev/sda"
          - name: "aprp09"
            devices:
            - name: "/dev/sda"
          - name: "aprp10"
            devices:
            - name: "/dev/sda"
          - name: "aprp11"
            devices:
            - name: "/dev/sda"
          - name: "aprp12"
            devices:
            - name: "/dev/sda"
    # cephBlockPools:
    #   - name: ceph-blockpool
    #     spec:
    #       failureDomain: host
    #       replicated:
    #         size: 3
    #     storageClass:
    #       enabled: true
    #       name: ceph-block
    #       isDefault: true
    #       reclaimPolicy: Delete
    #       allowVolumeExpansion: true
    #       parameters:
    #         imageFormat: "2"
    #         imageFeatures: layering
    #         csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
    #         csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    #         csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
    #         csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
    #         csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
    #         csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
    #         csi.storage.k8s.io/fstype: ext4
    # cephFileSystems:
    #   - name: ceph-filesystem
    #     spec:
    #       metadataPool:
    #         replicated:
    #           size: 3
    #       dataPools:
    #         - failureDomain: host
    #           replicated:
    #             size: 3
    #           name: data0
    #       metadataServer:
    #         activeCount: 1
    #         activeStandby: true
    #         resources:
    #           requests:
    #             cpu: 1000m
    #             memory: 4Gi
    #           limits:
    #             memory: 4Gi
    #     storageClass:
    #       enabled: true
    #       isDefault: false
    #       name: ceph-filesystem
    #       pool: data0
    #       reclaimPolicy: Delete
    #       allowVolumeExpansion: true
    #       parameters:
    #         csi.storage.k8s.io/provisioner-secret-name: rook-csi-cephfs-provisioner
    #         csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
    #         csi.storage.k8s.io/controller-expand-secret-name: rook-csi-cephfs-provisioner
    #         csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
    #         csi.storage.k8s.io/node-stage-secret-name: rook-csi-cephfs-node
    #         csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
    #         csi.storage.k8s.io/fstype: ext4
    cephObjectStores:
      - name: ceph-objectstore
        spec:
          metadataPool:
            failureDomain: host
            replicated:
              size: 3
          dataPool:
            failureDomain: host
            erasureCoded:
              dataChunks: 2
              codingChunks: 1
          preservePoolsOnDelete: true
          gateway:
            port: 80
            resources:
              requests:
                cpu: 1000m
                memory: 1Gi
              limits:
                memory: 2Gi
            instances: 1
          healthCheck:
            bucket:
              interval: 60s
        storageClass:
          enabled: true
          name: ceph-bucket
          reclaimPolicy: Delete
          parameters:
            region: us-east-1
