# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-ddns
    namespace: kube-system
type: Opaque
stringData:
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:PdFy+okhEcinndskwSMu3f7+,iv:Hl1XOZNWC1MQkx3mSUMUwXybx03ov0z3CLeg8LjMS4w=,tag:57tX6ejnt8vkcPmddij4dw==,type:str]
    CLOUDFLARE_APIKEY: ENC[AES256_GCM,data:gsEE4Zby8unoKRcDBrRXRjp310e5KyGLNk1PM/WE4ZranjVAUQ==,iv:0hQWDntPIG6EhFLUHsyDcr7SOdwsPB87LEfYc/y7r6U=,tag:4T2f3BbIixb8ighTTuaasg==,type:str]
    CLOUDFLARE_RECORD_NAME: ENC[AES256_GCM,data:/SRzuWeXQjBgMqxo8EyeOOjG,iv:1RWMVUapw/u3e+pZnpjD1FWY3ktCX6Ac97cCq3Y3moo=,tag:CKLgYZbF5Kx0r6mserQ3og==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k7h2z9xf64mlll8lg6gs9ua0qeslu3zu82s5k9my66cc2pnwd9qqkx5trs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkVndiSGxmZk1rUVozT3Iw
            VVhadnI4NEE2SU9wVjF4UU1WVVduRmErR2swCkY5azYrVW1oUnBHVllOMHQ3eE02
            K3RKcmxkMkFWY0dlQkxGUjhLOUNOZGcKLS0tIHFnekRXRWNvMmlQT3BtY0wrZVdM
            NEZIdktVWnlxWkpsM3FVcUZCRXB2clUKjXbopyLim0bGMQQnXoy0P3kIRvh/Mhnr
            IRDstH5KACW4ZWDbLm/Awuw2mIwN4oTm5gbn7+xEPAbFVd8y9BH73g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-07T23:08:35Z"
    mac: ENC[AES256_GCM,data:pzfhk/H2qK/TjqTLkh4ybTJu9eMqaG0HME2cV45/Ct5zAdsnWoMHu8ARfQ/zwgdunNHTRaenACaO6i6jMbb7gQuEzZaBEtG8TCejRNJpi5ASIGChTUJXXTTY2YWRyvSrDxIiD31kcHPjgrxw722h6tWQasenFr9oxlGtBMlvVxw=,iv:E8vKLah3G6eSzvWpd6IzQ0bgScibEX3VdBHG2pBLsF8=,tag:GBFccbcWJcCMtCc4ZtjoEw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
