kind: Secret
ansible_user: ENC[AES256_GCM,data:N/+CPcNf4NKkHg==,iv:CAIglfo3ufsA5c1NCL/zP7lcys81dpS5uAra1Nc6t6c=,tag:HBR0fGuNF4R/3c0j4GO4Bw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:L3WQeDeHkJsJXNI=,iv:J5wXNhn+rZkbiJ7NCMAQIRSTOVAXwPnlVmHhEPKf4+E=,tag:femcVVbBGWh6A5d7mUWwCQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1k7h2z9xf64mlll8lg6gs9ua0qeslu3zu82s5k9my66cc2pnwd9qqkx5trs
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRaHgvc3crVytOcUdmeDZF
            S0pjbklSU2FhdVpqWjlxNE1MWG5TUk9sSGhrCmxEaVF1NTJWclVmcTNiQ04vUFJR
            SzZkVXRjYThEM1NCS3JKS2NFQVY2V2cKLS0tIHBZOFU5ZzR4TVR1TnZiUVNCcTZx
            NVA5QnFyY3RBZm1Vbml2aFJURnJGKzQKk67odtwCoJinsgZexF4tE7vEVqnd7uri
            C4tQI1pEKbHsI7mMo0jWxhKjDay3DZ+oqeMnFWGcW8baFua7777jNQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-12-07T23:08:37Z"
    mac: ENC[AES256_GCM,data:3zA0FVpf7tRbni+w6XOBo5115EgQgpf6fwkRaEPbk2uiNIw08hYnrdgSbbyexJSKRDbMZyepZoZ0YSRVZLGu1PvaKgJOEMv3iN2kPRcrOtoICEMYj2bIFPTQocFp+a4P/8sC+Eaq6SmpTnv0uYR9XL0ElWYdTyAs9EL5/GxUToU=,iv:8HsMDxOywalg38tvN9cHTDkHkxk29n7Aj8YYHnZBU6I=,tag:TnAHilrOfQZFKNh+LPHaLg==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
