---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Los_Angeles
  METALLB_LB_RANGE: 10.50.50.200-10.50.50.250
  METALLB_K8S_GATEWAY_ADDR: 10.50.50.250
  METALLB_INGRESS_ADDR: 10.50.50.200
